package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1



/**
 * SmsEmpleado generated by hbm2java
 */
public class SmsEmpleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private SmsHojavida smsHojavida;
     private SmsUsuario smsUsuario;

    public SmsEmpleado() {
    }

	
    public SmsEmpleado(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }
    public SmsEmpleado(SmsHojavida smsHojavida, SmsUsuario smsUsuario) {
       this.smsHojavida = smsHojavida;
       this.smsUsuario = smsUsuario;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public SmsHojavida getSmsHojavida() {
        return this.smsHojavida;
    }
    
    public void setSmsHojavida(SmsHojavida smsHojavida) {
        this.smsHojavida = smsHojavida;
    }
    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }
    
    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }




}


