package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsHojavida generated by hbm2java
 */
public class SmsHojavida  implements java.io.Serializable {


     private Integer idHojaVida;
     private String hojaVidaNombre;
     private String hojaVidaTipo;
     private byte[] hojaVidaContenido;
     private Set<SmsEmpleado> smsEmpleados = new HashSet<SmsEmpleado>(0);

    public SmsHojavida() {
    }

    public SmsHojavida(String hojaVidaNombre, String hojaVidaTipo, byte[] hojaVidaContenido, Set<SmsEmpleado> smsEmpleados) {
       this.hojaVidaNombre = hojaVidaNombre;
       this.hojaVidaTipo = hojaVidaTipo;
       this.hojaVidaContenido = hojaVidaContenido;
       this.smsEmpleados = smsEmpleados;
    }
   
    public Integer getIdHojaVida() {
        return this.idHojaVida;
    }
    
    public void setIdHojaVida(Integer idHojaVida) {
        this.idHojaVida = idHojaVida;
    }
    public String getHojaVidaNombre() {
        return this.hojaVidaNombre;
    }
    
    public void setHojaVidaNombre(String hojaVidaNombre) {
        this.hojaVidaNombre = hojaVidaNombre;
    }
    public String getHojaVidaTipo() {
        return this.hojaVidaTipo;
    }
    
    public void setHojaVidaTipo(String hojaVidaTipo) {
        this.hojaVidaTipo = hojaVidaTipo;
    }
    public byte[] getHojaVidaContenido() {
        return this.hojaVidaContenido;
    }
    
    public void setHojaVidaContenido(byte[] hojaVidaContenido) {
        this.hojaVidaContenido = hojaVidaContenido;
    }
    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }
    
    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }




}


