package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsPermisos generated by hbm2java
 */
public class SmsPermisos  implements java.io.Serializable {


     private Integer idPermisos;
     private String permisosNombre;
     private String permisosDescripcion;
     private Set<SmsPermisosRol> smsPermisosRols = new HashSet<SmsPermisosRol>(0);

    public SmsPermisos() {
    }

    public SmsPermisos(String permisosNombre, String permisosDescripcion, Set<SmsPermisosRol> smsPermisosRols) {
       this.permisosNombre = permisosNombre;
       this.permisosDescripcion = permisosDescripcion;
       this.smsPermisosRols = smsPermisosRols;
    }
   
    public Integer getIdPermisos() {
        return this.idPermisos;
    }
    
    public void setIdPermisos(Integer idPermisos) {
        this.idPermisos = idPermisos;
    }
    public String getPermisosNombre() {
        return this.permisosNombre;
    }
    
    public void setPermisosNombre(String permisosNombre) {
        this.permisosNombre = permisosNombre;
    }
    public String getPermisosDescripcion() {
        return this.permisosDescripcion;
    }
    
    public void setPermisosDescripcion(String permisosDescripcion) {
        this.permisosDescripcion = permisosDescripcion;
    }
    public Set<SmsPermisosRol> getSmsPermisosRols() {
        return this.smsPermisosRols;
    }
    
    public void setSmsPermisosRols(Set<SmsPermisosRol> smsPermisosRols) {
        this.smsPermisosRols = smsPermisosRols;
    }




}


