package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1



/**
 * SmsPermisosRol generated by hbm2java
 */
public class SmsPermisosRol  implements java.io.Serializable {


     private Integer idPermisosRol;
     private SmsPermisos smsPermisos;
     private SmsRol smsRol;

    public SmsPermisosRol() {
    }

    public SmsPermisosRol(SmsPermisos smsPermisos, SmsRol smsRol) {
       this.smsPermisos = smsPermisos;
       this.smsRol = smsRol;
    }
   
    public Integer getIdPermisosRol() {
        return this.idPermisosRol;
    }
    
    public void setIdPermisosRol(Integer idPermisosRol) {
        this.idPermisosRol = idPermisosRol;
    }
    public SmsPermisos getSmsPermisos() {
        return this.smsPermisos;
    }
    
    public void setSmsPermisos(SmsPermisos smsPermisos) {
        this.smsPermisos = smsPermisos;
    }
    public SmsRol getSmsRol() {
        return this.smsRol;
    }
    
    public void setSmsRol(SmsRol smsRol) {
        this.smsRol = smsRol;
    }




}


