package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsRol generated by hbm2java
 */
public class SmsRol  implements java.io.Serializable {


     private Integer idRol;
     private String rolNombre;
     private Set<SmsUsuarioRol> smsUsuarioRols = new HashSet<SmsUsuarioRol>(0);
     private Set<SmsPermisosRol> smsPermisosRols = new HashSet<SmsPermisosRol>(0);

    public SmsRol() {
    }

    public SmsRol(String rolNombre, Set<SmsUsuarioRol> smsUsuarioRols, Set<SmsPermisosRol> smsPermisosRols) {
       this.rolNombre = rolNombre;
       this.smsUsuarioRols = smsUsuarioRols;
       this.smsPermisosRols = smsPermisosRols;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Set<SmsUsuarioRol> getSmsUsuarioRols() {
        return this.smsUsuarioRols;
    }
    
    public void setSmsUsuarioRols(Set<SmsUsuarioRol> smsUsuarioRols) {
        this.smsUsuarioRols = smsUsuarioRols;
    }
    public Set<SmsPermisosRol> getSmsPermisosRols() {
        return this.smsPermisosRols;
    }
    
    public void setSmsPermisosRols(Set<SmsPermisosRol> smsPermisosRols) {
        this.smsPermisosRols = smsPermisosRols;
    }




}


