package Model;
// Generated 24-oct-2015 11:24:40 by Hibernate Tools 4.3.1



/**
 * SmsUsuarioRol generated by hbm2java
 */
public class SmsUsuarioRol  implements java.io.Serializable {


     private Integer idUsuariosRol;
     private SmsRol smsRol;
     private SmsUsuario smsUsuario;

    public SmsUsuarioRol() {
    }

    public SmsUsuarioRol(SmsRol smsRol, SmsUsuario smsUsuario) {
       this.smsRol = smsRol;
       this.smsUsuario = smsUsuario;
    }
   
    public Integer getIdUsuariosRol() {
        return this.idUsuariosRol;
    }
    
    public void setIdUsuariosRol(Integer idUsuariosRol) {
        this.idUsuariosRol = idUsuariosRol;
    }
    public SmsRol getSmsRol() {
        return this.smsRol;
    }
    
    public void setSmsRol(SmsRol smsRol) {
        this.smsRol = smsRol;
    }
    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }
    
    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }




}


