package Modelo;
// Generated 26-nov-2015 15:26:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsHojavida generated by hbm2java
 */
public class SmsHojavida  implements java.io.Serializable {


     private Integer idHojaVida;
     private String hojaVidaNombre;
     private String hojaVidaRuta;
     private Set<SmsEmpleado> smsEmpleados = new HashSet<SmsEmpleado>(0);

    public SmsHojavida() {
    }

	
    public SmsHojavida(String hojaVidaNombre, String hojaVidaRuta) {
        this.hojaVidaNombre = hojaVidaNombre;
        this.hojaVidaRuta = hojaVidaRuta;
    }
    public SmsHojavida(String hojaVidaNombre, String hojaVidaRuta, Set<SmsEmpleado> smsEmpleados) {
       this.hojaVidaNombre = hojaVidaNombre;
       this.hojaVidaRuta = hojaVidaRuta;
       this.smsEmpleados = smsEmpleados;
    }
   
    public Integer getIdHojaVida() {
        return this.idHojaVida;
    }
    
    public void setIdHojaVida(Integer idHojaVida) {
        this.idHojaVida = idHojaVida;
    }
    public String getHojaVidaNombre() {
        return this.hojaVidaNombre;
    }
    
    public void setHojaVidaNombre(String hojaVidaNombre) {
        this.hojaVidaNombre = hojaVidaNombre;
    }
    public String getHojaVidaRuta() {
        return this.hojaVidaRuta;
    }
    
    public void setHojaVidaRuta(String hojaVidaRuta) {
        this.hojaVidaRuta = hojaVidaRuta;
    }
    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }
    
    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }




}


