package Modelo;
// Generated 17/11/2015 12:16:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SmsHojavida generated by hbm2java
 */
public class SmsHojavida implements java.io.Serializable {

    private Integer idHojaVida;
    private String hojaVidaNombre;
    private Set<SmsEmpleado> smsEmpleados = new HashSet<SmsEmpleado>(0);

    public SmsHojavida() {
    }

    public SmsHojavida(String hojaVidaNombre, Set<SmsEmpleado> smsEmpleados) {
        this.hojaVidaNombre = hojaVidaNombre;

        this.smsEmpleados = smsEmpleados;
    }

    public Integer getIdHojaVida() {
        return this.idHojaVida;
    }

    public void setIdHojaVida(Integer idHojaVida) {
        this.idHojaVida = idHojaVida;
    }

    public String getHojaVidaNombre() {
        return this.hojaVidaNombre;
    }

    public void setHojaVidaNombre(String hojaVidaNombre) {
        this.hojaVidaNombre = hojaVidaNombre;
    }

    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }

    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }

}
