package Modelo;
// Generated 26-nov-2015 15:26:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsProveedor generated by hbm2java
 */
public class SmsProveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private SmsUsuario smsUsuario;
     private Integer proveedorValorGanancia;
     private Set<SmsVehiculo> smsVehiculos = new HashSet<SmsVehiculo>(0);

    public SmsProveedor() {
    }

	
    public SmsProveedor(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }
    public SmsProveedor(SmsUsuario smsUsuario, Integer proveedorValorGanancia, Set<SmsVehiculo> smsVehiculos) {
       this.smsUsuario = smsUsuario;
       this.proveedorValorGanancia = proveedorValorGanancia;
       this.smsVehiculos = smsVehiculos;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }
    
    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }
    public Integer getProveedorValorGanancia() {
        return this.proveedorValorGanancia;
    }
    
    public void setProveedorValorGanancia(Integer proveedorValorGanancia) {
        this.proveedorValorGanancia = proveedorValorGanancia;
    }
    public Set<SmsVehiculo> getSmsVehiculos() {
        return this.smsVehiculos;
    }
    
    public void setSmsVehiculos(Set<SmsVehiculo> smsVehiculos) {
        this.smsVehiculos = smsVehiculos;
    }




}


