package Modelo;
// Generated 27-oct-2015 12:34:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsPais generated by hbm2java
 */
public class SmsPais  implements java.io.Serializable {


     private Integer idPais;
     private String paisNombre;
     private Set<SmsCiudad> smsCiudads = new HashSet<SmsCiudad>(0);

    public SmsPais() {
    }

    public SmsPais(String paisNombre, Set<SmsCiudad> smsCiudads) {
       this.paisNombre = paisNombre;
       this.smsCiudads = smsCiudads;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getPaisNombre() {
        return this.paisNombre;
    }
    
    public void setPaisNombre(String paisNombre) {
        this.paisNombre = paisNombre;
    }
    public Set<SmsCiudad> getSmsCiudads() {
        return this.smsCiudads;
    }
    
    public void setSmsCiudads(Set<SmsCiudad> smsCiudads) {
        this.smsCiudads = smsCiudads;
    }




}


