package Modelo;
// Generated 16-nov-2015 10:24:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsRol generated by hbm2java
 */
public class SmsRol  implements java.io.Serializable {


     private Integer idRol;
     private String rolNombre;
     private Set<SmsPermisos> smsPermisoses = new HashSet<SmsPermisos>(0);
     private Set<SmsUsuario> smsUsuarios = new HashSet<SmsUsuario>(0);

    public SmsRol() {
    }

    public SmsRol(String rolNombre, Set<SmsPermisos> smsPermisoses, Set<SmsUsuario> smsUsuarios) {
       this.rolNombre = rolNombre;
       this.smsPermisoses = smsPermisoses;
       this.smsUsuarios = smsUsuarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Set<SmsPermisos> getSmsPermisoses() {
        return this.smsPermisoses;
    }
    
    public void setSmsPermisoses(Set<SmsPermisos> smsPermisoses) {
        this.smsPermisoses = smsPermisoses;
    }
    public Set<SmsUsuario> getSmsUsuarios() {
        return this.smsUsuarios;
    }
    
    public void setSmsUsuarios(Set<SmsUsuario> smsUsuarios) {
        this.smsUsuarios = smsUsuarios;
    }




}


