package Modelo;
// Generated 26-nov-2015 15:26:50 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SmsReservacion generated by hbm2java
 */
public class SmsReservacion implements java.io.Serializable {

    private Integer idReservacion;
    private SmsCiudad smsCiudad;
    private SmsUsuario smsUsuario;
    private SmsVehiculo smsVehiculo;
    private SmsEmpleado smsEmpleado;
    private String reservacionLugarLlegada;
    private String reservacionLugarDestino;
    private String reservacionNotas;
    private Integer reservacionCosto;
    private Date reservacionFechaInicio;
    private Date reservacionFechaLlegada;
    private Date reservacionHoraInicio;
    private Date reservacionHoraLlegada;
    private Set<SmsCalificacion> smsCalificacions = new HashSet<SmsCalificacion>(0);

    public SmsReservacion() {
    }

    public SmsReservacion(SmsVehiculo smsVehiculo, SmsEmpleado smsEmpleado, SmsCiudad smsCiudad, SmsUsuario smsUsuario) {
        this.smsVehiculo = smsVehiculo;
        this.smsEmpleado = smsEmpleado;
        this.smsCiudad = smsCiudad;
        this.smsUsuario = smsUsuario;
    }

    public SmsReservacion(SmsVehiculo smsVehiculo, SmsEmpleado smsEmpleado, SmsCiudad smsCiudad, SmsUsuario smsUsuario, String reservacionLugarLlegada, String reservacionLugarDestino, String reservacionNotas, int reservacionCosto, Date reservacionFechaInicio, Date reservacionFechaLlegada, Date reservacionHoraInicio, Date reservacionHoraLlegada, Set<SmsCalificacion> smsCalificacions) {
        this.smsVehiculo = smsVehiculo;
        this.smsEmpleado = smsEmpleado;
        this.smsCiudad = smsCiudad;
        this.smsUsuario = smsUsuario;
        this.reservacionLugarLlegada = reservacionLugarLlegada;
        this.reservacionLugarDestino = reservacionLugarDestino;
        this.reservacionNotas = reservacionNotas;
        this.smsCalificacions = smsCalificacions;
        this.reservacionCosto = reservacionCosto;
        this.reservacionFechaInicio = reservacionFechaInicio;
        this.reservacionFechaLlegada = reservacionFechaLlegada;
        this.reservacionHoraInicio = reservacionHoraInicio;
        this.reservacionHoraLlegada = reservacionHoraLlegada;
    }

    public Integer getIdReservacion() {
        return this.idReservacion;
    }

    public void setIdReservacion(Integer idReservacion) {
        this.idReservacion = idReservacion;
    }

    public SmsVehiculo getSmsVehiculo() {
        return smsVehiculo;
    }

    public void setSmsVehiculo(SmsVehiculo smsVehiculo) {
        this.smsVehiculo = smsVehiculo;
    }

    public SmsEmpleado getSmsEmpleado() {
        return smsEmpleado;
    }

    public void setSmsEmpleado(SmsEmpleado smsEmpleado) {
        this.smsEmpleado = smsEmpleado;
    }

    public Date getReservacionFechaInicio() {
        return reservacionFechaInicio;
    }

    public void setReservacionFechaInicio(Date reservacionFechaInicio) {
        this.reservacionFechaInicio = reservacionFechaInicio;
    }

    public Date getReservacionFechaLlegada() {
        return reservacionFechaLlegada;
    }

    public void setReservacionFechaLlegada(Date reservacionFechaLlegada) {
        this.reservacionFechaLlegada = reservacionFechaLlegada;
    }

    public Date getReservacionHoraInicio() {
        return reservacionHoraInicio;
    }

    public void setReservacionHoraInicio(Date reservacionHoraInicio) {
        this.reservacionHoraInicio = reservacionHoraInicio;
    }

    public Date getReservacionHoraLlegada() {
        return reservacionHoraLlegada;
    }

    public void setReservacionHoraLlegada(Date reservacionHoraLlegada) {
        this.reservacionHoraLlegada = reservacionHoraLlegada;
    }    
    
    public SmsCiudad getSmsCiudad() {
        return this.smsCiudad;
    }

    public void setSmsCiudad(SmsCiudad smsCiudad) {
        this.smsCiudad = smsCiudad;
    }

    public SmsUsuario getSmsUsuario() {
        return this.smsUsuario;
    }

    public void setSmsUsuario(SmsUsuario smsUsuario) {
        this.smsUsuario = smsUsuario;
    }

    public String getReservacionLugarLlegada() {
        return this.reservacionLugarLlegada;
    }

    public void setReservacionLugarLlegada(String reservacionLugarLlegada) {
        this.reservacionLugarLlegada = reservacionLugarLlegada;
    }

    public String getReservacionLugarDestino() {
        return this.reservacionLugarDestino;
    }

    public void setReservacionLugarDestino(String reservacionLugarDestino) {
        this.reservacionLugarDestino = reservacionLugarDestino;
    }

    public String getReservacionNotas() {
        return this.reservacionNotas;
    }

    public void setReservacionNotas(String reservacionNotas) {
        this.reservacionNotas = reservacionNotas;
    }

    public Set<SmsCalificacion> getSmsCalificacions() {
        return this.smsCalificacions;
    }

    public void setSmsCalificacions(Set<SmsCalificacion> smsCalificacions) {
        this.smsCalificacions = smsCalificacions;
    }

    public Integer getReservacionCosto() {
        return reservacionCosto;
    }

    public void setReservacionCosto(Integer reservacionCosto) {
        this.reservacionCosto = reservacionCosto;
    }

    
}
