package Modelo;
// Generated 16-nov-2015 10:24:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SmsUsuario generated by hbm2java
 */
public class SmsUsuario  implements java.io.Serializable {


     private Integer idUsuario;
     private SmsCiudad smsCiudad;
     private String usuarioNombre;
     private String usuarioCc;
     private String usuarioTelefono;
     private String usuarioEmail;
     private String usuarioRazonSocial;
     private String usuarioNit;
     private String usuarioLogin;
     private String usuarioPassword;
     private String usuarioRememberToken;
     private Integer usuarioEstadoUsuario;
     private Set<SmsEmpleado> smsEmpleados = new HashSet<SmsEmpleado>(0);
     private Set<SmsProveedor> smsProveedors = new HashSet<SmsProveedor>(0);
     private Set<SmsReservacion> smsReservacions = new HashSet<SmsReservacion>(0);
     private Set<SmsRol> smsRols = new HashSet<SmsRol>(0);

    public SmsUsuario() {
    }

	
    public SmsUsuario(SmsCiudad smsCiudad) {
        this.smsCiudad = smsCiudad;
    }
    public SmsUsuario(SmsCiudad smsCiudad, String usuarioNombre, String usuarioCc, String usuarioTelefono, String usuarioEmail, String usuarioRazonSocial, String usuarioNit, String usuarioLogin, String usuarioPassword, String usuarioRememberToken, Integer usuarioEstadoUsuario, Set<SmsEmpleado> smsEmpleados, Set<SmsProveedor> smsProveedors, Set<SmsReservacion> smsReservacions, Set<SmsRol> smsRols) {
       this.smsCiudad = smsCiudad;
       this.usuarioNombre = usuarioNombre;
       this.usuarioCc = usuarioCc;
       this.usuarioTelefono = usuarioTelefono;
       this.usuarioEmail = usuarioEmail;
       this.usuarioRazonSocial = usuarioRazonSocial;
       this.usuarioNit = usuarioNit;
       this.usuarioLogin = usuarioLogin;
       this.usuarioPassword = usuarioPassword;
       this.usuarioRememberToken = usuarioRememberToken;
       this.usuarioEstadoUsuario = usuarioEstadoUsuario;
       this.smsEmpleados = smsEmpleados;
       this.smsProveedors = smsProveedors;
       this.smsReservacions = smsReservacions;
       this.smsRols = smsRols;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public SmsCiudad getSmsCiudad() {
        return this.smsCiudad;
    }
    
    public void setSmsCiudad(SmsCiudad smsCiudad) {
        this.smsCiudad = smsCiudad;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioCc() {
        return this.usuarioCc;
    }
    
    public void setUsuarioCc(String usuarioCc) {
        this.usuarioCc = usuarioCc;
    }
    public String getUsuarioTelefono() {
        return this.usuarioTelefono;
    }
    
    public void setUsuarioTelefono(String usuarioTelefono) {
        this.usuarioTelefono = usuarioTelefono;
    }
    public String getUsuarioEmail() {
        return this.usuarioEmail;
    }
    
    public void setUsuarioEmail(String usuarioEmail) {
        this.usuarioEmail = usuarioEmail;
    }
    public String getUsuarioRazonSocial() {
        return this.usuarioRazonSocial;
    }
    
    public void setUsuarioRazonSocial(String usuarioRazonSocial) {
        this.usuarioRazonSocial = usuarioRazonSocial;
    }
    public String getUsuarioNit() {
        return this.usuarioNit;
    }
    
    public void setUsuarioNit(String usuarioNit) {
        this.usuarioNit = usuarioNit;
    }
    public String getUsuarioLogin() {
        return this.usuarioLogin;
    }
    
    public void setUsuarioLogin(String usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }
    public String getUsuarioPassword() {
        return this.usuarioPassword;
    }
    
    public void setUsuarioPassword(String usuarioPassword) {
        this.usuarioPassword = usuarioPassword;
    }
    public String getUsuarioRememberToken() {
        return this.usuarioRememberToken;
    }
    
    public void setUsuarioRememberToken(String usuarioRememberToken) {
        this.usuarioRememberToken = usuarioRememberToken;
    }
    public Integer getUsuarioEstadoUsuario() {
        return this.usuarioEstadoUsuario;
    }
    
    public void setUsuarioEstadoUsuario(Integer usuarioEstadoUsuario) {
        this.usuarioEstadoUsuario = usuarioEstadoUsuario;
    }
    public Set<SmsEmpleado> getSmsEmpleados() {
        return this.smsEmpleados;
    }
    
    public void setSmsEmpleados(Set<SmsEmpleado> smsEmpleados) {
        this.smsEmpleados = smsEmpleados;
    }
    public Set<SmsProveedor> getSmsProveedors() {
        return this.smsProveedors;
    }
    
    public void setSmsProveedors(Set<SmsProveedor> smsProveedors) {
        this.smsProveedors = smsProveedors;
    }
    public Set<SmsReservacion> getSmsReservacions() {
        return this.smsReservacions;
    }
    
    public void setSmsReservacions(Set<SmsReservacion> smsReservacions) {
        this.smsReservacions = smsReservacions;
    }
    public Set<SmsRol> getSmsRols() {
        return this.smsRols;
    }
    
    public void setSmsRols(Set<SmsRol> smsRols) {
        this.smsRols = smsRols;
    }




}


